config/routes.rb
Rails.application.routes.draw do
  # devise
  devise_for :users, skip: 'sessions', controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_scope :user do
    get	'/users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post	'/users/sign_in', to: 'users/sessions#create', as: :user_session
    get	'/users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  # Defines the root path route ("/")
  root "home#index"

  # all restaurants list
  get '/all', to: 'restaurants#show_all', as: :all_restaurants

  # all restaurants list by area
  get '/all/area/:id', to: 'restaurants#show_all_by_area', as: :all_restaurants_area

  # all restaurants list by genre
  get '/all/genre/:id', to: 'restaurants#show_all_by_genre', as: :all_restaurants_genre

  # restaurant detail page
  get '/restaurant/:id', to: 'restaurants#show_detail', as: :show_restaurant

  # search restaurant
  get '/search', to: 'restaurants#search_restaurant', as: :search_restaurant

  # keep restaurant
  post '/users/:id/restaurants/:restaurant_id/keep', to: 'keeps#keep_restaurant', as: :keep_restaurant

  # remove keep restaurant
  delete '/users/:id/restaurants/:restaurant_id/remove', to: 'keeps#remove_keep_restaurant', as: :remove_keep_restaurant

  # keep restaurant by user
  get 'users/:id/keeps', to: 'users#show_all_keeps', as: :show_all_keeps
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # relation
   mount_uploader :profile_image, ProfileImageUploader
   has_many :keeps
   has_many :restaurants, through: :keeps
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show_all_keeps
    user = User.find(params[:id])
    @restaurants = user.restaurants.page(params[:page]).per(20)
    @heading_word = user.name + 'さんの保存済のお店'

    render :keeps
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/keeps.html.erb
<%= render partial: 'shared/page_title', locals: { page_title: "#{@current_user.name}さんの保存済のお店" } %>

<div class="list">
  <div class="wrap-sm">
    <h2 class="list__heading">保存済みのお店</h2>
    <div class="list__contents">
      <% @restaurants.each do |restaurant| %>
      <%= link_to show_restaurant_path(restaurant), class: 'contents', target: :blank do %>
      <div class="list__item flex">
        <div class="list__img">
          <% if restaurant.image? %>
          <%= image_tag restaurant.image.url %>
          <% end %>
        </div>
        <div class="list__mass">
          <% if check_keep_restaurant(@current_user, restaurant.id) %>
          <%= button_to remove_keep_restaurant_path(@current_user.id, restaurant.id), method: :delete, class: 'contents' do %>
          <span title="<%= check_keep_restaurant(@current_user, restaurant.id) ? 'このお店の保存を外す' : 'このお店を保存する' %>" class="<%= 'done' if check_keep_restaurant(@current_user, restaurant.id) %>"><i class="far fa-bookmark fa-border"></i></span>
          <% end %>
          <% else %>
          <%= button_to keep_restaurant_path(@current_user.id, restaurant.id), method: :post, class: 'contents' do %>
          <span title="<%= check_keep_restaurant(@current_user, restaurant.id) ? 'このお店の保存を外す' : 'このお店を保存する' %>" class="<%= 'done' if check_keep_restaurant(@current_user, restaurant.id) %>"><i class="far fa-bookmark fa-border"></i></span>
          <% end %>
          <% end %>
          <h3><%= restaurant.name %></h3>
          <p>
            <%= restaurant.area.name %>&nbsp;/&nbsp;<%= restaurant.genre.name %>
          </p>
          <div class="basic-rule"></div>
          <p>
            <%= restaurant.remarks %>
          </p>
        </div>
      </div>
      <% end %>
      <% end %>
      <%= paginate @restaurants %>
    </div>
  </div>
</div>